### ISSUE TITLE
באג- קיצור מקשים לא פעיל עבור איתור 0.1.9.1

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria-dev-channel#19]
יש באג בגירסה 0.1.9.1 שקיצור מקשים לא פעיל עבור איתור, הקיצור המיועד לו כפול עם ספריה
ואם בוחרים קיצור לאיתור זה נהיה אוטומטי גם עבור ספריה וכן הפוך.
לפנינו ניתן לראות איך כל פעם זה נקבע אוטומטי עבור שניהם.
![מצגת1](https://github.com/user-attachments/assets/2622fe85-bfb7-44e7-a4e1-0598d5a5a9cd)

**Comment by Sivan22** [comment]
תיקנתי, תודה על הדיווח.

בתאריך יום ב׳, 19 באוג׳ 2024, 16:54, מאת IEUDI ***@***.***>:
